### ISSUE TITLE
there is no example about  camera

### ISSUE THREAD

**Issue by ljx0517** [cocos-creator/example-cases#353]
please add a example about camere

**Comment by 2youyou2** [comment]
Hi,
There is camera example in this repo: https://github.com/cocos-creator/demo-camera

**Comment by jareguo** [comment]
@2youyou2 
![image](https://user-images.githubusercontent.com/1503156/27723002-5da7f60c-5d9d-11e7-8b19-206de2fbe211.png)
既然做了新 demo，就加进来吧

**Comment by 2youyou2** [comment]
@nantas 做的。。
