### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by raksa** [cocos-creator/example-cases#366]
i just clone and open, then get warning

 **Script attached to "mask" in scene "TestList.fire" is missing or invalid. Detailed information:
Node path: "Menu/readme/mask"
Asset url: "db://assets/TestList.fire"**

**Comment by knoxHuang** [comment]
Are you pulling the latest branches?（master？）

**Comment by raksa** [comment]
yes i cloned it today, last 3 hours

**Comment by knoxHuang** [comment]
You pull the latest branch and try it on.

**Comment by raksa** [comment]
i'm on the latest one, you can see

![untitled](https://user-images.githubusercontent.com/4116021/28768009-4207cf50-7600-11e7-9ffb-3ec06af297c1.png)

**Comment by knoxHuang** [comment]
Clear the console, and then double-click the TestList scene or will it appear?

**Comment by raksa** [comment]
it still show warning

**Comment by knoxHuang** [comment]
It might be a mismatch with engine.
it's better to create example-case with Creator

http://cocos2d-x.org/docs/editors_and_tools/creator-chapters/getting-started/dashboard/index.html

**Comment by raksa** [comment]
i'm using 1.5.2

by the way @knoxHuang, you should clone it and reopen. to see whether there any problem on first open

**Comment by knoxHuang** [comment]
You can check whether the 'Testlist' node has missing scripts, then delete it.

**Comment by raksa** [comment]
yes one node has a missing script,

**Comment by jareguo** [comment]
The latest version of example is for 1.6, if you are using 1.5, you should create the example project in creator.

**Comment by raksa** [comment]
ok
