### ISSUE TITLE
TypeError: Cannot read property 'WebSocket' of undefined on cocos creator 1.8.0

### ISSUE THREAD

**Issue by haxpor** [cocos-creator/example-cases#404]
I encountered this problem after exporting the project, and run on 微信开发者工具 `v1.02.1801081`

![screen shot 2018-01-12 at 9 05 41 am](https://user-images.githubusercontent.com/673757/34854994-456d89c4-f778-11e7-9986-622965f9e92e.png)

**Comment by jareguo** [comment]
It's a bug about the Wechat Dev Tool. You can modify the socket.io to workaround.
```
var global = ... return this; ...
// change to
var global = ... return window; ...
```

**Comment by haxpor** [comment]
Thank you! It works now.
