### ISSUE TITLE
1.91 版本运行报错啊

### ISSUE THREAD

**Issue by xian-qing** [cocos-creator/example-cases#455]
downloader.js:70 GET http://localhost:7456/preview-scripts/assets/cases/anysdk/08_adtracking/AdTracking.js 0 ()

**Comment by jareguo** [comment]
这是你的浏览器的广告过滤插件阻止了该 js 文件的下载，请检查浏览器相关设置。

**Comment by jareguo** [comment]
请 @ColinCollins  修改范例，防止在 url 中出现 ad 字样

**Comment by jareguo** [comment]
谢谢反馈，范例已更新
