### ISSUE TITLE
build-template should sync the changes with cocos2d-x-lite/template

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/example-cases#488]
when example-cases build native project, it used the template of cocos2d-x-lite, not those.

**Comment by ColinCollins** [comment]
Those files are used to cover the engine original template files, so we need to keep them in the example-case in order to make the example scene feature will be ok

**Comment by drelaptop** [comment]
what's the `engine original template files`, do you means template in cocos2d-x-lite? and what time the cover behavior occurs, can you describe it in detail.

**Comment by ColinCollins** [comment]
yes， when we build the project to native platform, the editor will check the build-template folder if there any file could be cover, the editor will help you to do that

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/41770794-ca8e6ac8-7645-11e8-8858-aae78c7368d0.png)
those files will cover the original files that in cocos2d-x-lite
 
![image](https://user-images.githubusercontent.com/35832931/41770857-f7ad1978-7645-11e8-9439-e9db99e3c382.png)

**Comment by drelaptop** [comment]
so what's the meaning to do this work? keep both template is not convenient to maintain. and the `build-template` folder have not changed for 2 years.

you can compare the ` AppActivity.java` between `build-template` and `template` to see the difference. some changes isn't sync to `build-template/.../AppActivity.java`

**Comment by ColinCollins** [comment]
I tried how this part of the feature to work just now ...
![image](https://user-images.githubusercontent.com/35832931/41828139-2787c298-7866-11e8-9cc7-8443427e493b.png)
That is the example-case, I built to the Android platform. There has been added a new fold named proj.android and check the proj.android-studio you will find its AppActivity.cpp has been covered by the files that exist in proj.android.
![image](https://user-images.githubusercontent.com/35832931/41828204-94378b30-7866-11e8-830a-fb9421f60394.png)

**Comment by ColinCollins** [comment]
I think those files do not get any change because this part of feature has not got any change for two years.

**Comment by drelaptop** [comment]
thanks for explain, it shouldn't be removed, but modified, I will change the title.

`build-template/.../AppActivity.java` should sync the changes with `build/AppActivity.java`

**Comment by ColinCollins** [comment]
ok, I already get what's kind of problem will happen if we did not fixe the AppActivity.java with this pr
https://github.com/cocos-creator/cocos2d-x-lite/pull/808
and as I just test, that problem still exists.
