### ISSUE TITLE
研发场景合并工具

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/example-cases#500]
运行机制，参考 https://docs.unity3d.com/Manual/SmartMerge.html

**Comment by ColinCollins** [comment]
暂时没有想法。。。明天再试

**Comment by ColinCollins** [comment]
今天研究感觉难点在 Unity 用了一个 exe 的文件内容然后适配了多家流行的合作仓库工具，首先 gitkaren 是不行了，我用 sourceTree 在做实验似乎。

**Comment by jareguo** [comment]
不会吧，这个是通用的，什么工具都能用

**Comment by ColinCollins** [comment]
现阶段第一步：
构建一个 gulp 的命令内容，通过命令行实现分支场景的合并。
传入参数设置为 <fileName>, <newBranchName>， [isKeepOriginChange]， [dirFoldName] 三个吧.
fileName 为场景文件名称，
newBranchName 需要合并的分支名称，
isKeepOriginChange boolean 内容 默认为 false，新分支内容覆盖原有分支内容，
dirFoldName 指定的缓存文件输出文件夹，缓存文件为 fire 文件的正常排序内容，可填项，默认当前文件夹。若有指定文件夹，就将文件内容保存到指定文件夹。
conflict 冲突内容：
1. 针对两个 fire 文件获取后排序，逐行对比判断，不相同的内容直接覆盖，新生成的 fire 文件缓存在 dirFold 文件夹下。

**Comment by ColinCollins** [comment]
1. readfileSync-> create String -> match ([])-> sort use the id -> write to a new File

**Comment by ColinCollins** [comment]
排序设计格式：
_id 总内容排序-> 主键
node: ——id—— 匹配对应节点 -> propertype

**Comment by ColinCollins** [comment]
完成一个部分的内容排序之后，components 的排序放弃，因为考虑到同一节点的多个 component 内容无法正确的排序，所以这个部分采用局部循环查找对应部分进行内容对比。
nodes 的排序是为了方便对比，减少循环消耗，无法排序的部分就只能进行消耗。
（这里用 find 多消耗一下内存记录一下绑定的 components 到每个 nodes 上，可以考虑按照 --type-- 设计排序）
有了一个部分的排序之后获取剩下的两个排序。
进行对比，内容的覆盖。
完成之后设计输出文件样式。

**Comment by ColinCollins** [comment]
流程设计：
获取了 sort 三个文件内容，首先命名是相同的，路径的选取在当前文件夹下创建新的文件夹 mergeSpace
将生成的文件导入，判断是否冲突，若是冲突打开现有的合并工具进行整理，继续进入下一步。
merge.fire 文件名称与源文件相同，并且排序按照  __id__ 获取原先的排序内容。

**Comment by ColinCollins** [comment]
最后一步+结构调整：
1.经过重新的设计发现，传入的 base 应该是按照单个文件存在的，所以清除以前针对 array 的循环操作，改为针对单个文件操作。
2.针对设计在 package 添加了新的 proto ， dependMergeTool 属性包含暂存文件路径以及调用工具。
3.目前对于 fire 文件以及非 fire 文件内容都进行了考虑，最后针对不同的数据输出路径进行调整。
4.进入 fire.merge 文件重新排序部分，也是最后一个部分了。排序规则，保持原有的节点树顺序，componets 内容针对对应节点顺序进行排序。

**Comment by ColinCollins** [comment]
目前瓶颈在重新规划数据内容，把之前没有考虑到的 __id__ 排序重新考虑进去。
我觉得目前考虑代码简化精简会给构建进度带来很大的困难，尤其是在知识储备不够丰富的前提下。
因此暂时不考虑代码精简内容，以完成功能实现为主。

**Comment by ColinCollins** [comment]
第一阶段完结，撒花，现在开始进入‘测试’发布阶段

**Comment by jareguo** [comment]
请把你的 json 格式贴上来，简单介绍一下

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/42622308-acd2a76c-85f2-11e8-95d2-c0a3624f131d.png)
当前生成 json 文件的对比格式是如上图，比较特殊的冲突问题是针对 _id 数据的比较，目前没有特别好的办法调整。

_components 是当前节点的绑定组件内容
_clickEvent 是根据特殊的组件绑定的 clickEvent 记录，我通过 comp clickEvent [] 获取记录之后关联到当前绑定组件的节点上。
冲突对比过程中，尽量减少了 __id__ 的存在，
解决冲突完成后，json 文件会根据 children 内容重新排版 node 生成以场景内节点树顺序相应的 fire 文件
经过实验测试了两个场景：
1.9.3 的 webp-test。
2.0 的 TestList (调整过，场景内添加了所有的功能组件)。
最后结果是：场景稳定打开，绑定内容都在。

**Comment by ColinCollins** [comment]
1. 合并 example-case v1.9-release 到 master 分支。
2. 实际上使用 sourceTree 合并我认为应该先发布 npm 的包，确保内容是可以被调用的在进行场景合并测试。
3.场景合并只针对有冲突的场景文件进行调整。

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/42723559-b0f2062a-8792-11e8-81e6-3a60265b05ad.png)
mark 设置成为 JSON 的形式之后再 locationID mark 转换 id 的过程中会出现 JSON 无法解析的情况，因为本身。
这样只能通过先转换为一般数据在通过添加 ‘’ 包裹使对象成为字符串，在经过转换获得能够转换的 JSON 脚本。

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/42724259-988dce98-87a1-11e8-9a6f-cc776f489e49.png)
这个部分匹配字符串十分糟糕。。。
![Uploading image.png…]()
因为在输出文件的时候要以字符串的形式，所以原本就是 json 格式的字符串进行了二次封装成为 string
导致最上图的糟糕的比较。不好看啊

**Comment by ColinCollins** [comment]
目前测试了几个场景基本上都通过了，调试完成之后融合生成的场景可以正常的打开并且功能正常。
但是因为不是发布工具的原因吧，sourceTree 会重新扫描生成的 fire 文件，并对文件进行重新的编辑。
接下来的工作我想尝试着将工具与 sourceTree 进行合并。即发布当前版本工具并在 sourceTree 设置内进行调试。

**Comment by ColinCollins** [comment]
在制作 pipe 内容的过程中，思考到关于排序的问题。 现在第一阶段排序，即针对三个对比文件的排序规则是按照 __id__ 表示排序，实际上算是按照 type: cc.Type 这样的方式进行排序。主要是根据 Node 属性，但是转换 merge 文件的时候我会进行一次节点树的排序，我认为可以将节点树的这个排序方案直接提前，将三个对比文件也按照节点树的顺序进行排列。因为这样生成出来的数据是有依据的（根据 _children _parent 什么的）。

**Comment by ColinCollins** [comment]
总体上是开发完毕了。。。
由于目前 NPM 无法发布新的 package 所以暂时无法连接 SourceTree 直接使用。
所以暂时需要等待。
