### ISSUE TITLE
[Request] remove proj.android files for creator2.0

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/example-cases#507]
with this changes, https://github.com/cocos-creator/cocos2d-x-lite/pull/1352

those below should be removed for ant project and binary template removed

<img width="400" alt="example-case" src="https://user-images.githubusercontent.com/26329291/42144525-1b8adb8c-7dee-11e8-86dc-1aca1be170e4.png">

## suggestion [Optional]

Since only one file `AppActivity.java` existed at build-templates dir, don't need to put both copy into jsb-default and jsb-link. Only one file, one copy is ok. copy it into different dir when build

please check this @jareguo

**Comment by jareguo** [comment]
LGTM
