### ISSUE TITLE
[完善] 过滤 example-cases 中所有范例并且进行完善

### ISSUE THREAD

**Issue by knoxHuang** [cocos-creator/example-cases#524]
在 2.0 分支上进行改进完善

- [x] 补充例用 TTF 字体展示 Label 测试。
- [x] 剔除没用的代码（之前做 tips 有遗留了一些多余的代码）
- [x] 添加远程加载音频的范例 [用户反馈传送门](http://forum.cocos.com/t/cocos/64054)
- [x] 添加动态加载 spine 范例 [用户反馈传送门](http://forum.cocos.com/t/2-0-spine/64039)

**Comment by ColinCollins** [comment]
你这个传送门太瞥了，我进不去啊。。。。

**Comment by pandamicro** [comment]
没事，你不用进去，做就对可

**Comment by ColinCollins** [comment]
cc.sys: 
isNative: {
不包括： 微信小游戏（平台），微信，Web_DeskTop， Web_Mobile(手机浏览器）
包括： android，ios 
}
isMobile:{
不包括：微信小游戏，Web_DeskTop
包括： 微信，手机浏览器，android，ios
}
isBrowser:{
只有： Desktop_Browser, Web_Mobile_Browser
}

**Comment by ColinCollins** [comment]
修改 Tips 代码 
AnySDK 部分的场景我认为应该保留 SuspensionTips
针对继承 BaseAnySDKExample 内容脚本进行修改，删除 hasSupport() 判断就 ok 了

**Comment by ColinCollins** [comment]
http://forum.cocos.com/t/iphonex-bug/65412 Canvas 适配模式
http://forum.cocos.com/t/2-0-1-dragonbones/65402 动态加载 DragonBones

**Comment by ColinCollins** [comment]
sys.platform 平台判断：
![image](https://user-images.githubusercontent.com/35832931/45989544-c5318700-c0ae-11e8-9f87-fc59676df890.png)
isNative = CC_JSB > Android | IOS | IPAD | WP8 | TIZEN | BLACKBERRY
isBrowser = window(Object)
判断条件优先级按照上图顺序依次往下。
else 中判断内容为：
![image](https://user-images.githubusercontent.com/35832931/45989648-222d3d00-c0af-11e8-8c8e-c7e9040609a9.png)
判断是否是 mobile 分辨浏览器类型
