### ISSUE TITLE
example-02/09_videoPlayer 展示的当前视频状态与 online video 不符合

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/example-cases#553]
相关 https://github.com/cocos-creator/fireball/issues/8006

**Comment by drelaptop** [comment]
在 creator 1.10 中，发布 example-cases 的 android 工程，打开测试例 example-02/09_videoPlayer 时，显示的状态类似上图，【6】处是 ready to play 此时只是本地视频的状态准备好了，和远程视频没关系。这时候点击 play online ，远程视频才开始加载，在加载的过程中（可能会耗时 20s），此时显示的状态依旧是 ready to play，实际上远程视频没有准备好。

换一个方式说，就是测试例本身表现不出来远程视频的加载过程，造成容易让测试人员误解，点击 play online 就会立即播放远程视频。@jareguo

![video-error-state](https://user-images.githubusercontent.com/26329291/43563005-941b24e0-9652-11e8-9e8f-6f0ad6fde87a.png)

**Comment by drelaptop** [comment]
或许把 play to online video 改成 switch resource to remote/local 更合适，因为其它的 button 对远程资源同样有效，每次 switch 的时候清空状态，收到消息后再更新状态。

如果更改的话，这个 button 的回调中就不用调用 play() 了，switch 之后需要手动点击 play 才会播放，在点击 play 的时候，如果 READY_TO_PLAY 消息还没收到，可以弹个通知提醒资源没加载完成。

这样和最初的设想一致，并且状态的反馈非常清晰

![zl-video-reply](https://user-images.githubusercontent.com/26329291/43565811-b512ab44-965e-11e8-9ef8-206b8ba295fc.png)

**Comment by jareguo** [comment]
明白了，不错的建议，就这么改吧
