### ISSUE TITLE
将所有范例的 Background Prefab 节点设置为自动同步

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/example-cases#575]
目前是手动同步的，其实 TestList 中的背景色已经调整过了。不过其它范例都没变，要一个一个改过去吗…… 疯了。还是用自动同步吧，这样以后换背景的时候就不用重新设置。

提交到 v2.0，记得提交后提醒所有人更新一下仓库，免得造成冲突

**Comment by ColinCollins** [comment]
ok
