### ISSUE TITLE
完善 downloader-web 范例

### ISSUE THREAD

**Issue by knoxHuang** [cocos-creator/example-cases#576]
- [ ] ![image](https://user-images.githubusercontent.com/7564028/45075046-5b116c00-b118-11e8-96ec-c3dad603e9d3.png)

---------------------------------------------------------------------------------------------------

- [ ] ![image](https://user-images.githubusercontent.com/7564028/45075095-85632980-b118-11e8-9d33-d3a941fe8f41.png)

---------------------------------------------------------------------------------------------------

- [ ] 检查微信小游戏是否会有该问题
![image](https://user-images.githubusercontent.com/7564028/45075099-8bf1a100-b118-11e8-8831-33d61a0a1fc1.png)

---------------------------------------------------------------------------------------------------

- [ ] ![image](https://user-images.githubusercontent.com/7564028/45075114-9f047100-b118-11e8-9503-2990aee8982a.png)

https://github.com/cocos-creator/fireball/issues/8352
https://github.com/cocos-creator/fireball/issues/8351
https://github.com/cocos-creator/fireball/issues/8350
https://github.com/cocos-creator/fireball/issues/8345

**Comment by knoxHuang** [comment]
上一页修改为：滑动进入下一页
下一页修改为：滑动进入上一页

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/45075167-cf4c0f80-b118-11e8-8240-862e1b6bd550.png)
请用正常一点的图片。当你看到 Unreal 用这种图片做 demo 你会做何感想？
