### ISSUE TITLE
webview 测试例初始时 Label 显示的状态与实际不符

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/example-cases#608]
## 在桌面端 Chrome 浏览器验证，刚打开 webview 测试例，窗口白框（状态应该是正在加载），显示的却是 Loaded

![webview-case-stats-error](https://user-images.githubusercontent.com/26329291/46661899-9eb23680-cbec-11e8-8eda-115c7d3234f5.png)

**Comment by drelaptop** [comment]
### 第二个问题 WebView 的 EditBox 输入框在 Android & iOS 输入不展示，点 visit 可以获取到数据。此时 EditBox 的测试例效果正常

> 不了解两个输入框有什么区别，需要检查

**Comment by ColinCollins** [comment]
问题反馈：
原生平台的 label 数据无法正常显示，原因是 CCCanvasRenderingContext2D 的字体设置 Des 解析出了问题。
![image](https://user-images.githubusercontent.com/35832931/46798975-18315c80-cd86-11e8-9ec7-656a5a3f310d.png)
建议修改为：
![image](https://user-images.githubusercontent.com/35832931/46799547-9d694100-cd87-11e8-83fb-f1f4a2642e03.png)


(^(bold|italic)?)\\s{0,1}(\\d|.)+px\\s{1}([\\w-]+|\"[\\w -]+\"$)

**Comment by drelaptop** [comment]
Label 的问题修复了。初始状态时 is Loaded 的问题，有空看一下吗 @ColinCollins ，web 上的行为也是这样

**Comment by ColinCollins** [comment]
在看了 webview 添加监听是在 default load 之后的，改一下顺序就 ok 了，等下提 pr
