### ISSUE TITLE
Import from Spine Pro

### ISSUE THREAD

**Issue by balazsnemeth** [cocos-creator/example-cases#668]
Hi!

I only found this old documentation on how to import spine animation:
https://github.com/cocos-creator/deprecated-examples/blob/master/guides/components/spine_skeleton.md

Is this now officially supported?
I found spineBoy png, json and atlas file in this repository, is this a valid and working example now (beginning fo 2019)

Thank you @nantas @walzer @pandamicro @zilongshanren

**Comment by jareguo** [comment]
It's supported officially. You can open the "assets/cases/spine" folder in the project and refer to it.
See https://docs.cocos2d-x.org/creator/manual/en/asset-workflow/spine.html for more details.
